config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, :book_suggestions

  root to: 'books#index'

  get '/books', to: 'books#index', as: 'all_books'
  get '/books/unread', to: 'books#unread', as: 'unread_books'
  get '/books/read', to: 'books#read', as: 'read_books'

  patch '/book_suggestions/:id/approve', to: 'book_suggestions#approve', as: 'approve_book_suggestion'
  delete '/book_suggestions/:id/reject', to: 'book_suggestions#reject', as: 'reject_book_suggestion'
  post '/book_suggestions/:id/add_to_library', to: 'books#add_to_library', as: 'add_to_library'

  # Define your application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/book_suggestion.rb
class BookSuggestion < ApplicationRecord
    # Add any necessary validations or associations here
    attr_accessor :pending_approval
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


def member?
return role_id == 0
end

def admin?
  return role_id == 1
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_suggestions_controller.rb
class BookSuggestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authenticate_admin!, only: [:approve, :reject]

  def index
    @book_suggestions = BookSuggestion.all
  end

  def new
    @book_suggestion = BookSuggestion.new
  end


  def show
    @book_suggestion = BookSuggestion.find(params[:id])
  end
  

  def create
    @book_suggestion = BookSuggestion.new(book_params)
    @book_suggestion.suggested_by = current_user.email
    if @book_suggestion.save
      flash[:notice] = "Thank you for your book suggestion! It will be reviewed by an admin before being added to the library."
      redirect_to root_path
    else
      render :new
    end
  end

  def approve
    @book_suggestion = BookSuggestion.find(params[:id])
    @book_suggestion.update(pending_approval: false)
  
    # Create a new book based on the approved suggestion
    Book.create(title: @book_suggestion.title)
  
    # Delete the approved book suggestion
    @book_suggestion.destroy
  
    redirect_to books_path, notice: 'Book suggestion has been approved and added to the books index.'
  end
  

  def reject
    @book_suggestion = BookSuggestion.find(params[:id])
    @book_suggestion.destroy
    redirect_to book_suggestions_path, notice: 'Book suggestion has been rejected.'
  end

  def authenticate_admin!
    unless current_user&.admin?
      redirect_to root_path, alert: 'Access denied. You must be an admin to perform this action.'
    end
  end
  private

  def book_params
    params.require(:book_suggestion).permit(:title, :description)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /books or /books.json
  def index
    @books = Book.all
  end

  def recommendations
    @recommended_books = Book.recommended 
  end
  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    if current_user.admin?
    @book = Book.new
    else
      redirect_to root_path, notice: "You do not have the capability of adding a new book."
  end
end
  # GET /books/1/edit
  def edit
    if current_user.admin?
  
      else
        redirect_to root_path, notice: "You do not have the capability of editing a book."
    end
  end

  # POST /books or /books.json
  def create
    if current_user.admin?
      @book = Book.new(book_params)
      if @book.save
        redirect_to @book, notice: 'Book was successfully created.'
      else
        render :new
      end
    else
      @book_suggestion = BookSuggestion.new(book_params)
      @book_suggestion.suggested_by = current_user.email
      @book_suggestion.pending_approval = true
      if @book_suggestion.save
        flash[:notice] = "Thank you for your book suggestion! It will be reviewed by an admin before being added to the library."
        redirect_to root_path
      else
        render :new
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # DELETE /books/1 or /books/1.json
  def destroy

    if current_user.admin?
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  else
    redirect_to root_path, notice: "You do not have the capability of deleting a book."
  end
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find_by(id: params[:id])
  unless @book
    if params[:id] == "read"
      @books = Book.where(read: true)
    elsif params[:id] == "unread"
      @books = Book.where(read: false)
    end
    render :index
  end
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :read, :pending)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_suggestions_helper.rb
module BookSuggestionsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/book_suggestions/create.html.erb
<h1>New Book Suggestion</h1>

<%= form_with model: @book_suggestion, url: book_suggestions_path, method: :post do |form| %>
  <% if @book_suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_suggestion.errors.count, "error") %> prohibited this book suggestion from being saved:</h2>
      <ul>
        <% @book_suggestion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <%= form.submit "Submit" %>
<% end %>

<%= link_to "Back", book_suggestions_path %>


<% end %>

app/views/book_suggestions/index.html.erb
<h1>Book Suggestions</h1>

<% @book_suggestions.each do |book_suggestion| %>
  <div id="<%= dom_id book_suggestion %>">
    <p>
      <strong>Title:</strong>
      <%= book_suggestion.title %>
    </p>


    <% if current_user.admin? %>
      <%= form_tag approve_book_suggestion_path(book_suggestion), method: :patch do %>
        <%= submit_tag "Approve" %>
      <% end %>

      <%= form_tag reject_book_suggestion_path(book_suggestion), method: :delete, data: { confirm: "Are you sure you want to reject this suggestion?" } do %>
        <%= submit_tag "Reject" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/book_suggestions/new.html.erb
<h1>New Book Suggestion</h1>

<%= form_with model: @book_suggestion, url: book_suggestions_path, method: :post do |form| %>
  <% if @book_suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_suggestion.errors.count, "error") %> prohibited this book suggestion from being saved:</h2>
      <ul>
        <% @book_suggestion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <%= form.submit "Submit" %>
<% end %>

app/views/book_suggestions/show.html.erb
<h1>Book Suggestions</h1>

<% @book_suggestion.each do |book_suggestion| %>
  <div id="<%= dom_id book_suggestion %>">
    <p>
      <strong>Title:</strong>
      <%= book_suggestion.title %>
    </p>


        <p>
      <strong>Description:</strong>
      <%= book_suggestion.description %>
    </p>

    <p>


   <% if current_user.admin?  %>
  <%= form_tag approve_book_suggestion_path(book_suggestion), method: :patch do %>
    <%= submit_tag "Approve" %>
  <% end %>
  
  <%= form_tag reject_book_suggestion_path(book_suggestion), method: :delete, data: { confirm: "Are you sure you want to reject this suggestion?" } do %>
    <%= submit_tag "Reject" %>
  <% end %>
<% end %>

  </div>
<% end %>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">

  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Read:</strong>
    <%= book.read %>
  </p>

  <p>
    <strong>Pending:</strong>
    <%= book.pending %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :read, style: "display: block" %>
    <%= form.check_box :read %>
  </div>

  <div>
    <%= form.label :pending, style: "display: block" %>
    <%= form.check_box :pending %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<% if current_user.admin? %>
  <%= link_to "New book", new_book_path %>
<% else %>
  <%= link_to "New book recommendation", new_book_suggestion_path %>
<% end %>



<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/read.html.erb
<p style="color: green"><%= notice %></p>

<h1>Read Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
    </p>
  <% end %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>

app/views/books/unread.html.erb
<p style="color: green"><%= notice %></p>

<h1>Unread Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
    
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookaholics 2.0</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <strong>Navigation: </strong>
    <div class="nav-link">
    <%= link_to 'Home', root_path %> -
    <%= link_to 'All Books', books_path %> -
    <%= link_to 'Unread Books', unread_books_path %> -
    <%= link_to 'Read Books', read_books_path %> -
     <%= link_to 'All Book Suggestions', book_suggestions_path %> -
  


      <% if user_signed_in? %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
            <a href="/users/sign_in">Sign In</a> 
      <% end %>
    </div>
    <% if flash[:error] %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>